// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipfs_lite.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class TTEAddParams;
@class TTEBlock;
@class TTELink;
@class TTENode;
@class TTENodeStat;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - TTEIpfsLiteRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface TTEIpfsLiteRoot : GPBRootObject
@end

#pragma mark - TTEAddParams

typedef GPB_ENUM(TTEAddParams_FieldNumber) {
  TTEAddParams_FieldNumber_Layout = 1,
  TTEAddParams_FieldNumber_Chunker = 2,
  TTEAddParams_FieldNumber_RawLeaves = 3,
  TTEAddParams_FieldNumber_Hidden = 4,
  TTEAddParams_FieldNumber_Shared = 5,
  TTEAddParams_FieldNumber_NoCopy = 6,
  TTEAddParams_FieldNumber_HashFun = 7,
};

@interface TTEAddParams : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *layout;

@property(nonatomic, readwrite, copy, null_resettable) NSString *chunker;

@property(nonatomic, readwrite) BOOL rawLeaves;

@property(nonatomic, readwrite) BOOL hidden;

@property(nonatomic, readwrite) BOOL shared;

@property(nonatomic, readwrite) BOOL noCopy;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashFun;

@end

#pragma mark - TTEBlock

typedef GPB_ENUM(TTEBlock_FieldNumber) {
  TTEBlock_FieldNumber_RawData = 1,
  TTEBlock_FieldNumber_Cid = 2,
};

@interface TTEBlock : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *rawData;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - TTELink

typedef GPB_ENUM(TTELink_FieldNumber) {
  TTELink_FieldNumber_Name = 1,
  TTELink_FieldNumber_Size = 2,
  TTELink_FieldNumber_Cid = 3,
};

@interface TTELink : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) int64_t size;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - TTENodeStat

typedef GPB_ENUM(TTENodeStat_FieldNumber) {
  TTENodeStat_FieldNumber_Hash_p = 1,
  TTENodeStat_FieldNumber_NumLinks = 2,
  TTENodeStat_FieldNumber_BlockSize = 3,
  TTENodeStat_FieldNumber_LinksSize = 4,
  TTENodeStat_FieldNumber_DataSize = 5,
  TTENodeStat_FieldNumber_CumulativeSize = 6,
};

@interface TTENodeStat : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *hash_p;

@property(nonatomic, readwrite) int32_t numLinks;

@property(nonatomic, readwrite) int32_t blockSize;

@property(nonatomic, readwrite) int32_t linksSize;

@property(nonatomic, readwrite) int32_t dataSize;

@property(nonatomic, readwrite) int32_t cumulativeSize;

@end

#pragma mark - TTENode

typedef GPB_ENUM(TTENode_FieldNumber) {
  TTENode_FieldNumber_Block = 1,
  TTENode_FieldNumber_LinksArray = 2,
  TTENode_FieldNumber_Stat = 3,
  TTENode_FieldNumber_Size = 4,
};

@interface TTENode : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TTEBlock *block;
/** Test to see if @c block has been set. */
@property(nonatomic, readwrite) BOOL hasBlock;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TTELink*> *linksArray;
/** The number of items in @c linksArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger linksArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) TTENodeStat *stat;
/** Test to see if @c stat has been set. */
@property(nonatomic, readwrite) BOOL hasStat;

@property(nonatomic, readwrite) int64_t size;

@end

#pragma mark - TTEAddFileRequest

typedef GPB_ENUM(TTEAddFileRequest_FieldNumber) {
  TTEAddFileRequest_FieldNumber_AddParams = 1,
  TTEAddFileRequest_FieldNumber_Chunk = 2,
};

typedef GPB_ENUM(TTEAddFileRequest_Payload_OneOfCase) {
  TTEAddFileRequest_Payload_OneOfCase_GPBUnsetOneOfCase = 0,
  TTEAddFileRequest_Payload_OneOfCase_AddParams = 1,
  TTEAddFileRequest_Payload_OneOfCase_Chunk = 2,
};

@interface TTEAddFileRequest : GPBMessage

@property(nonatomic, readonly) TTEAddFileRequest_Payload_OneOfCase payloadOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) TTEAddParams *addParams;

@property(nonatomic, readwrite, copy, null_resettable) NSData *chunk;

@end

/**
 * Clears whatever value was set for the oneof 'payload'.
 **/
void TTEAddFileRequest_ClearPayloadOneOfCase(TTEAddFileRequest *message);

#pragma mark - TTEAddFileResponse

typedef GPB_ENUM(TTEAddFileResponse_FieldNumber) {
  TTEAddFileResponse_FieldNumber_Node = 1,
};

@interface TTEAddFileResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TTENode *node;
/** Test to see if @c node has been set. */
@property(nonatomic, readwrite) BOOL hasNode;

@end

#pragma mark - TTEGetFileRequest

typedef GPB_ENUM(TTEGetFileRequest_FieldNumber) {
  TTEGetFileRequest_FieldNumber_Cid = 1,
};

@interface TTEGetFileRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - TTEGetFileResponse

typedef GPB_ENUM(TTEGetFileResponse_FieldNumber) {
  TTEGetFileResponse_FieldNumber_Chunk = 1,
};

@interface TTEGetFileResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *chunk;

@end

#pragma mark - TTEAddNodeRequest

typedef GPB_ENUM(TTEAddNodeRequest_FieldNumber) {
  TTEAddNodeRequest_FieldNumber_Block = 1,
};

@interface TTEAddNodeRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TTEBlock *block;
/** Test to see if @c block has been set. */
@property(nonatomic, readwrite) BOOL hasBlock;

@end

#pragma mark - TTEAddNodeResponse

@interface TTEAddNodeResponse : GPBMessage

@end

#pragma mark - TTEAddNodesRequest

typedef GPB_ENUM(TTEAddNodesRequest_FieldNumber) {
  TTEAddNodesRequest_FieldNumber_BlocksArray = 1,
};

@interface TTEAddNodesRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TTEBlock*> *blocksArray;
/** The number of items in @c blocksArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger blocksArray_Count;

@end

#pragma mark - TTEAddNodesResponse

@interface TTEAddNodesResponse : GPBMessage

@end

#pragma mark - TTEGetNodeRequest

typedef GPB_ENUM(TTEGetNodeRequest_FieldNumber) {
  TTEGetNodeRequest_FieldNumber_Cid = 1,
};

@interface TTEGetNodeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - TTEGetNodeResponse

typedef GPB_ENUM(TTEGetNodeResponse_FieldNumber) {
  TTEGetNodeResponse_FieldNumber_Node = 1,
};

@interface TTEGetNodeResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TTENode *node;
/** Test to see if @c node has been set. */
@property(nonatomic, readwrite) BOOL hasNode;

@end

#pragma mark - TTEGetNodesRequest

typedef GPB_ENUM(TTEGetNodesRequest_FieldNumber) {
  TTEGetNodesRequest_FieldNumber_CidsArray = 1,
};

@interface TTEGetNodesRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *cidsArray;
/** The number of items in @c cidsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cidsArray_Count;

@end

#pragma mark - TTEGetNodesResponse

typedef GPB_ENUM(TTEGetNodesResponse_FieldNumber) {
  TTEGetNodesResponse_FieldNumber_Node = 1,
  TTEGetNodesResponse_FieldNumber_Error = 2,
};

typedef GPB_ENUM(TTEGetNodesResponse_Option_OneOfCase) {
  TTEGetNodesResponse_Option_OneOfCase_GPBUnsetOneOfCase = 0,
  TTEGetNodesResponse_Option_OneOfCase_Node = 1,
  TTEGetNodesResponse_Option_OneOfCase_Error = 2,
};

@interface TTEGetNodesResponse : GPBMessage

@property(nonatomic, readonly) TTEGetNodesResponse_Option_OneOfCase optionOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) TTENode *node;

@property(nonatomic, readwrite, copy, null_resettable) NSString *error;

@end

/**
 * Clears whatever value was set for the oneof 'option'.
 **/
void TTEGetNodesResponse_ClearOptionOneOfCase(TTEGetNodesResponse *message);

#pragma mark - TTERemoveNodeRequest

typedef GPB_ENUM(TTERemoveNodeRequest_FieldNumber) {
  TTERemoveNodeRequest_FieldNumber_Cid = 1,
};

@interface TTERemoveNodeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - TTERemoveNodeResponse

@interface TTERemoveNodeResponse : GPBMessage

@end

#pragma mark - TTERemoveNodesRequest

typedef GPB_ENUM(TTERemoveNodesRequest_FieldNumber) {
  TTERemoveNodesRequest_FieldNumber_CidsArray = 1,
};

@interface TTERemoveNodesRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *cidsArray;
/** The number of items in @c cidsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cidsArray_Count;

@end

#pragma mark - TTERemoveNodesResponse

@interface TTERemoveNodesResponse : GPBMessage

@end

#pragma mark - TTEResolveLinkRequest

typedef GPB_ENUM(TTEResolveLinkRequest_FieldNumber) {
  TTEResolveLinkRequest_FieldNumber_NodeCid = 1,
  TTEResolveLinkRequest_FieldNumber_PathArray = 2,
};

@interface TTEResolveLinkRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *nodeCid;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *pathArray;
/** The number of items in @c pathArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pathArray_Count;

@end

#pragma mark - TTEResolveLinkResponse

typedef GPB_ENUM(TTEResolveLinkResponse_FieldNumber) {
  TTEResolveLinkResponse_FieldNumber_Link = 1,
  TTEResolveLinkResponse_FieldNumber_RemainingPathArray = 2,
};

@interface TTEResolveLinkResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TTELink *link;
/** Test to see if @c link has been set. */
@property(nonatomic, readwrite) BOOL hasLink;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *remainingPathArray;
/** The number of items in @c remainingPathArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger remainingPathArray_Count;

@end

#pragma mark - TTETreeRequest

typedef GPB_ENUM(TTETreeRequest_FieldNumber) {
  TTETreeRequest_FieldNumber_NodeCid = 1,
  TTETreeRequest_FieldNumber_Path = 2,
  TTETreeRequest_FieldNumber_Depth = 3,
};

@interface TTETreeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *nodeCid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

@property(nonatomic, readwrite) int32_t depth;

@end

#pragma mark - TTETreeResponse

typedef GPB_ENUM(TTETreeResponse_FieldNumber) {
  TTETreeResponse_FieldNumber_PathsArray = 1,
};

@interface TTETreeResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *pathsArray;
/** The number of items in @c pathsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pathsArray_Count;

@end

#pragma mark - TTEDeleteBlockRequest

typedef GPB_ENUM(TTEDeleteBlockRequest_FieldNumber) {
  TTEDeleteBlockRequest_FieldNumber_Cid = 1,
};

@interface TTEDeleteBlockRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - TTEDeleteBlockResponse

@interface TTEDeleteBlockResponse : GPBMessage

@end

#pragma mark - TTEHasBlockRequest

typedef GPB_ENUM(TTEHasBlockRequest_FieldNumber) {
  TTEHasBlockRequest_FieldNumber_Cid = 1,
};

@interface TTEHasBlockRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - TTEHasBlockResponse

typedef GPB_ENUM(TTEHasBlockResponse_FieldNumber) {
  TTEHasBlockResponse_FieldNumber_HasBlock = 1,
};

@interface TTEHasBlockResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasBlock;

@end

#pragma mark - TTEGetBlockRequest

typedef GPB_ENUM(TTEGetBlockRequest_FieldNumber) {
  TTEGetBlockRequest_FieldNumber_Cid = 1,
};

@interface TTEGetBlockRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - TTEGetBlockResponse

typedef GPB_ENUM(TTEGetBlockResponse_FieldNumber) {
  TTEGetBlockResponse_FieldNumber_Block = 1,
};

@interface TTEGetBlockResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TTEBlock *block;
/** Test to see if @c block has been set. */
@property(nonatomic, readwrite) BOOL hasBlock;

@end

#pragma mark - TTEGetBlockSizeRequest

typedef GPB_ENUM(TTEGetBlockSizeRequest_FieldNumber) {
  TTEGetBlockSizeRequest_FieldNumber_Cid = 1,
};

@interface TTEGetBlockSizeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - TTEGetBlockSizeResponse

typedef GPB_ENUM(TTEGetBlockSizeResponse_FieldNumber) {
  TTEGetBlockSizeResponse_FieldNumber_Size = 1,
};

@interface TTEGetBlockSizeResponse : GPBMessage

@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - TTEPutBlockRequest

typedef GPB_ENUM(TTEPutBlockRequest_FieldNumber) {
  TTEPutBlockRequest_FieldNumber_Block = 1,
};

@interface TTEPutBlockRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) TTEBlock *block;
/** Test to see if @c block has been set. */
@property(nonatomic, readwrite) BOOL hasBlock;

@end

#pragma mark - TTEPutBlockResponse

@interface TTEPutBlockResponse : GPBMessage

@end

#pragma mark - TTEPutBlocksRequest

typedef GPB_ENUM(TTEPutBlocksRequest_FieldNumber) {
  TTEPutBlocksRequest_FieldNumber_BlocksArray = 1,
};

@interface TTEPutBlocksRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<TTEBlock*> *blocksArray;
/** The number of items in @c blocksArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger blocksArray_Count;

@end

#pragma mark - TTEPutBlocksResponse

@interface TTEPutBlocksResponse : GPBMessage

@end

#pragma mark - TTEAllKeysRequest

@interface TTEAllKeysRequest : GPBMessage

@end

#pragma mark - TTEAllKeysResponse

typedef GPB_ENUM(TTEAllKeysResponse_FieldNumber) {
  TTEAllKeysResponse_FieldNumber_Cid = 1,
};

@interface TTEAllKeysResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - TTEHashOnReadRequest

typedef GPB_ENUM(TTEHashOnReadRequest_FieldNumber) {
  TTEHashOnReadRequest_FieldNumber_HashOnRead = 1,
};

@interface TTEHashOnReadRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hashOnRead;

@end

#pragma mark - TTEHashOnReadResponse

@interface TTEHashOnReadResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
