// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ipfs_lite.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class AddParams;
@class Block;
@class Link;
@class Node;
@class NodeStat;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - IpfsLiteRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface IpfsLiteRoot : GPBRootObject
@end

#pragma mark - AddParams

typedef GPB_ENUM(AddParams_FieldNumber) {
  AddParams_FieldNumber_Layout = 1,
  AddParams_FieldNumber_Chunker = 2,
  AddParams_FieldNumber_RawLeaves = 3,
  AddParams_FieldNumber_Hidden = 4,
  AddParams_FieldNumber_Shared = 5,
  AddParams_FieldNumber_NoCopy = 6,
  AddParams_FieldNumber_HashFun = 7,
};

@interface AddParams : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *layout;

@property(nonatomic, readwrite, copy, null_resettable) NSString *chunker;

@property(nonatomic, readwrite) BOOL rawLeaves;

@property(nonatomic, readwrite) BOOL hidden;

@property(nonatomic, readwrite) BOOL shared;

@property(nonatomic, readwrite) BOOL noCopy;

@property(nonatomic, readwrite, copy, null_resettable) NSString *hashFun;

@end

#pragma mark - Block

typedef GPB_ENUM(Block_FieldNumber) {
  Block_FieldNumber_RawData = 1,
  Block_FieldNumber_Cid = 2,
};

@interface Block : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *rawData;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - Link

typedef GPB_ENUM(Link_FieldNumber) {
  Link_FieldNumber_Name = 1,
  Link_FieldNumber_Size = 2,
  Link_FieldNumber_Cid = 3,
};

@interface Link : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

@property(nonatomic, readwrite) int64_t size;

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - NodeStat

typedef GPB_ENUM(NodeStat_FieldNumber) {
  NodeStat_FieldNumber_Hash_p = 1,
  NodeStat_FieldNumber_NumLinks = 2,
  NodeStat_FieldNumber_BlockSize = 3,
  NodeStat_FieldNumber_LinksSize = 4,
  NodeStat_FieldNumber_DataSize = 5,
  NodeStat_FieldNumber_CumulativeSize = 6,
};

@interface NodeStat : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *hash_p;

@property(nonatomic, readwrite) int32_t numLinks;

@property(nonatomic, readwrite) int32_t blockSize;

@property(nonatomic, readwrite) int32_t linksSize;

@property(nonatomic, readwrite) int32_t dataSize;

@property(nonatomic, readwrite) int32_t cumulativeSize;

@end

#pragma mark - Node

typedef GPB_ENUM(Node_FieldNumber) {
  Node_FieldNumber_Block = 1,
  Node_FieldNumber_LinksArray = 2,
  Node_FieldNumber_Stat = 3,
  Node_FieldNumber_Size = 4,
};

@interface Node : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Block *block;
/** Test to see if @c block has been set. */
@property(nonatomic, readwrite) BOOL hasBlock;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Link*> *linksArray;
/** The number of items in @c linksArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger linksArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NodeStat *stat;
/** Test to see if @c stat has been set. */
@property(nonatomic, readwrite) BOOL hasStat;

@property(nonatomic, readwrite) int64_t size;

@end

#pragma mark - AddFileRequest

typedef GPB_ENUM(AddFileRequest_FieldNumber) {
  AddFileRequest_FieldNumber_AddParams = 1,
  AddFileRequest_FieldNumber_Chunk = 2,
};

typedef GPB_ENUM(AddFileRequest_Payload_OneOfCase) {
  AddFileRequest_Payload_OneOfCase_GPBUnsetOneOfCase = 0,
  AddFileRequest_Payload_OneOfCase_AddParams = 1,
  AddFileRequest_Payload_OneOfCase_Chunk = 2,
};

@interface AddFileRequest : GPBMessage

@property(nonatomic, readonly) AddFileRequest_Payload_OneOfCase payloadOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) AddParams *addParams;

@property(nonatomic, readwrite, copy, null_resettable) NSData *chunk;

@end

/**
 * Clears whatever value was set for the oneof 'payload'.
 **/
void AddFileRequest_ClearPayloadOneOfCase(AddFileRequest *message);

#pragma mark - AddFileResponse

typedef GPB_ENUM(AddFileResponse_FieldNumber) {
  AddFileResponse_FieldNumber_Node = 1,
};

@interface AddFileResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Node *node;
/** Test to see if @c node has been set. */
@property(nonatomic, readwrite) BOOL hasNode;

@end

#pragma mark - GetFileRequest

typedef GPB_ENUM(GetFileRequest_FieldNumber) {
  GetFileRequest_FieldNumber_Cid = 1,
};

@interface GetFileRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - GetFileResponse

typedef GPB_ENUM(GetFileResponse_FieldNumber) {
  GetFileResponse_FieldNumber_Chunk = 1,
};

@interface GetFileResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSData *chunk;

@end

#pragma mark - AddNodeRequest

typedef GPB_ENUM(AddNodeRequest_FieldNumber) {
  AddNodeRequest_FieldNumber_Block = 1,
};

@interface AddNodeRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Block *block;
/** Test to see if @c block has been set. */
@property(nonatomic, readwrite) BOOL hasBlock;

@end

#pragma mark - AddNodeResponse

@interface AddNodeResponse : GPBMessage

@end

#pragma mark - AddNodesRequest

typedef GPB_ENUM(AddNodesRequest_FieldNumber) {
  AddNodesRequest_FieldNumber_BlocksArray = 1,
};

@interface AddNodesRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Block*> *blocksArray;
/** The number of items in @c blocksArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger blocksArray_Count;

@end

#pragma mark - AddNodesResponse

@interface AddNodesResponse : GPBMessage

@end

#pragma mark - GetNodeRequest

typedef GPB_ENUM(GetNodeRequest_FieldNumber) {
  GetNodeRequest_FieldNumber_Cid = 1,
};

@interface GetNodeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - GetNodeResponse

typedef GPB_ENUM(GetNodeResponse_FieldNumber) {
  GetNodeResponse_FieldNumber_Node = 1,
};

@interface GetNodeResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Node *node;
/** Test to see if @c node has been set. */
@property(nonatomic, readwrite) BOOL hasNode;

@end

#pragma mark - GetNodesRequest

typedef GPB_ENUM(GetNodesRequest_FieldNumber) {
  GetNodesRequest_FieldNumber_CidsArray = 1,
};

@interface GetNodesRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *cidsArray;
/** The number of items in @c cidsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cidsArray_Count;

@end

#pragma mark - GetNodesResponse

typedef GPB_ENUM(GetNodesResponse_FieldNumber) {
  GetNodesResponse_FieldNumber_Node = 1,
  GetNodesResponse_FieldNumber_Error = 2,
};

typedef GPB_ENUM(GetNodesResponse_Option_OneOfCase) {
  GetNodesResponse_Option_OneOfCase_GPBUnsetOneOfCase = 0,
  GetNodesResponse_Option_OneOfCase_Node = 1,
  GetNodesResponse_Option_OneOfCase_Error = 2,
};

@interface GetNodesResponse : GPBMessage

@property(nonatomic, readonly) GetNodesResponse_Option_OneOfCase optionOneOfCase;

@property(nonatomic, readwrite, strong, null_resettable) Node *node;

@property(nonatomic, readwrite, copy, null_resettable) NSString *error;

@end

/**
 * Clears whatever value was set for the oneof 'option'.
 **/
void GetNodesResponse_ClearOptionOneOfCase(GetNodesResponse *message);

#pragma mark - RemoveNodeRequest

typedef GPB_ENUM(RemoveNodeRequest_FieldNumber) {
  RemoveNodeRequest_FieldNumber_Cid = 1,
};

@interface RemoveNodeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - RemoveNodeResponse

@interface RemoveNodeResponse : GPBMessage

@end

#pragma mark - RemoveNodesRequest

typedef GPB_ENUM(RemoveNodesRequest_FieldNumber) {
  RemoveNodesRequest_FieldNumber_CidsArray = 1,
};

@interface RemoveNodesRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *cidsArray;
/** The number of items in @c cidsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger cidsArray_Count;

@end

#pragma mark - RemoveNodesResponse

@interface RemoveNodesResponse : GPBMessage

@end

#pragma mark - ResolveLinkRequest

typedef GPB_ENUM(ResolveLinkRequest_FieldNumber) {
  ResolveLinkRequest_FieldNumber_NodeCid = 1,
  ResolveLinkRequest_FieldNumber_PathArray = 2,
};

@interface ResolveLinkRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *nodeCid;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *pathArray;
/** The number of items in @c pathArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pathArray_Count;

@end

#pragma mark - ResolveLinkResponse

typedef GPB_ENUM(ResolveLinkResponse_FieldNumber) {
  ResolveLinkResponse_FieldNumber_Link = 1,
  ResolveLinkResponse_FieldNumber_RemainingPathArray = 2,
};

@interface ResolveLinkResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Link *link;
/** Test to see if @c link has been set. */
@property(nonatomic, readwrite) BOOL hasLink;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *remainingPathArray;
/** The number of items in @c remainingPathArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger remainingPathArray_Count;

@end

#pragma mark - TreeRequest

typedef GPB_ENUM(TreeRequest_FieldNumber) {
  TreeRequest_FieldNumber_NodeCid = 1,
  TreeRequest_FieldNumber_Path = 2,
  TreeRequest_FieldNumber_Depth = 3,
};

@interface TreeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *nodeCid;

@property(nonatomic, readwrite, copy, null_resettable) NSString *path;

@property(nonatomic, readwrite) int32_t depth;

@end

#pragma mark - TreeResponse

typedef GPB_ENUM(TreeResponse_FieldNumber) {
  TreeResponse_FieldNumber_PathsArray = 1,
};

@interface TreeResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *pathsArray;
/** The number of items in @c pathsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger pathsArray_Count;

@end

#pragma mark - DeleteBlockRequest

typedef GPB_ENUM(DeleteBlockRequest_FieldNumber) {
  DeleteBlockRequest_FieldNumber_Cid = 1,
};

@interface DeleteBlockRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - DeleteBlockResponse

@interface DeleteBlockResponse : GPBMessage

@end

#pragma mark - HasBlockRequest

typedef GPB_ENUM(HasBlockRequest_FieldNumber) {
  HasBlockRequest_FieldNumber_Cid = 1,
};

@interface HasBlockRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - HasBlockResponse

typedef GPB_ENUM(HasBlockResponse_FieldNumber) {
  HasBlockResponse_FieldNumber_HasBlock = 1,
};

@interface HasBlockResponse : GPBMessage

@property(nonatomic, readwrite) BOOL hasBlock;

@end

#pragma mark - GetBlockRequest

typedef GPB_ENUM(GetBlockRequest_FieldNumber) {
  GetBlockRequest_FieldNumber_Cid = 1,
};

@interface GetBlockRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - GetBlockResponse

typedef GPB_ENUM(GetBlockResponse_FieldNumber) {
  GetBlockResponse_FieldNumber_Block = 1,
};

@interface GetBlockResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Block *block;
/** Test to see if @c block has been set. */
@property(nonatomic, readwrite) BOOL hasBlock;

@end

#pragma mark - GetBlockSizeRequest

typedef GPB_ENUM(GetBlockSizeRequest_FieldNumber) {
  GetBlockSizeRequest_FieldNumber_Cid = 1,
};

@interface GetBlockSizeRequest : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - GetBlockSizeResponse

typedef GPB_ENUM(GetBlockSizeResponse_FieldNumber) {
  GetBlockSizeResponse_FieldNumber_Size = 1,
};

@interface GetBlockSizeResponse : GPBMessage

@property(nonatomic, readwrite) int32_t size;

@end

#pragma mark - PutBlockRequest

typedef GPB_ENUM(PutBlockRequest_FieldNumber) {
  PutBlockRequest_FieldNumber_Block = 1,
};

@interface PutBlockRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) Block *block;
/** Test to see if @c block has been set. */
@property(nonatomic, readwrite) BOOL hasBlock;

@end

#pragma mark - PutBlockResponse

@interface PutBlockResponse : GPBMessage

@end

#pragma mark - PutBlocksRequest

typedef GPB_ENUM(PutBlocksRequest_FieldNumber) {
  PutBlocksRequest_FieldNumber_BlocksArray = 1,
};

@interface PutBlocksRequest : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<Block*> *blocksArray;
/** The number of items in @c blocksArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger blocksArray_Count;

@end

#pragma mark - PutBlocksResponse

@interface PutBlocksResponse : GPBMessage

@end

#pragma mark - AllKeysRequest

@interface AllKeysRequest : GPBMessage

@end

#pragma mark - AllKeysResponse

typedef GPB_ENUM(AllKeysResponse_FieldNumber) {
  AllKeysResponse_FieldNumber_Cid = 1,
};

@interface AllKeysResponse : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *cid;

@end

#pragma mark - HashOnReadRequest

typedef GPB_ENUM(HashOnReadRequest_FieldNumber) {
  HashOnReadRequest_FieldNumber_HashOnRead = 1,
};

@interface HashOnReadRequest : GPBMessage

@property(nonatomic, readwrite) BOOL hashOnRead;

@end

#pragma mark - HashOnReadResponse

@interface HashOnReadResponse : GPBMessage

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
